services:
  orbit:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - ISAACSIM_VERSION=${ISAACSIM_VERSION}
        - ISAACSIM_PATH=${DOCKER_ISAACSIM_PATH}
        - DOCKER_USER_HOME=${DOCKER_USER_HOME}
    image: orbit
    container_name: orbit
    env_file:
      - .env
    environment:
      - ISAACSIM_PATH=${DOCKER_ISAACSIM_PATH}
    volumes:
      - type: bind
        source: ~/.ssh
        target: /root/.ssh
      - type: bind
        source: ~/.gitconfig
        target: /root/.gitconfig
      - type: bind
        source: ../
        target: /workspace/orbit
      - type: volume
        source: isaac-cache-kit
        target: ${DOCKER_ISAACSIM_PATH}/kit/cache
      - type: volume
        source: isaac-cache-ov
        target: ${DOCKER_USER_HOME}/.cache/ov
      - type: volume
        source: isaac-cache-pip
        target: ${DOCKER_USER_HOME}/.cache/pip
      - type: volume
        source: isaac-cache-gl
        target: ${DOCKER_USER_HOME}/.cache/nvidia/GLCache
      - type: volume
        source: isaac-cache-compute
        target: ${DOCKER_USER_HOME}/.nv/ComputeCache
      - type: volume
        source: isaac-logs
        target: ${DOCKER_USER_HOME}/.nvidia-omniverse/logs
      - type: volume
        source: isaac-carb-logs
        target: ${DOCKER_ISAACSIM_PATH}/kit/logs/Kit/Isaac-Sim
      - type: volume
        source: isaac-data
        target: ${DOCKER_USER_HOME}/.local/share/ov/data
      - type: volume
        source: isaac-docs
        target: ${DOCKER_USER_HOME}/Documents
      # Optional X11 Forwarding volumes commented out
      #- type: bind
      #  source: /tmp/.X11-unix
      #  target: /tmp/.X11-unix
      #- type: bind
      #  source: ${HOME}/.Xauthority
      #  target: ${DOCKER_USER_HOME}/.Xauthority
      - type: volume
        source: orbit-docs
        target: /workspace/orbit/docs/_build
      - type: volume
        source: orbit-logs
        target: /workspace/orbit/logs
      - type: volume
        source: orbit-data
        target: /workspace/orbit/data_storage
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    entrypoint: bash
    stdin_open: true
    tty: true

volumes:
  isaac-cache-kit: {}
  isaac-cache-ov: {}
  isaac-cache-pip: {}
  isaac-cache-gl: {}
  isaac-cache-compute: {}
  isaac-logs: {}
  isaac-carb-logs: {}
  isaac-data: {}
  isaac-docs: {}
  orbit-docs: {}
  orbit-logs: {}
  orbit-data: {}
